//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace HoungBNB.DataModels
{
	/// <summary>
	/// Database       : BNB17db
	/// Data Source    : C:\Users\inf05074\Desktop\HoungBNB\HoungBNB\DataModels../../App_Data/BNB17db.mdb
	/// Server Version : 04.00.0000
	/// </summary>
	public partial class BNB17dbDB : LinqToDB.Data.DataConnection
	{
		public ITable<About> Abouts { get { return this.GetTable<About>(); } }
		public ITable<News>  News   { get { return this.GetTable<News>(); } }
		public ITable<Order> Orders { get { return this.GetTable<Order>(); } }

		public BNB17dbDB()
		{
			InitDataContext();
		}

		public BNB17dbDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("about")]
	public partial class About
	{
		[Column(),        PrimaryKey, Identity] public int    No           { get; set; } // Long
		[Column("About"), Nullable            ] public string About_Column { get; set; } // text(255)
	}

	[Table("News")]
	public partial class News
	{
		[PrimaryKey, Identity] public int       No          { get; set; } // Long
		[Column,     Nullable] public DateTime? PublishDate { get; set; } // DateTime
		[Column,     Nullable] public string    Title       { get; set; } // text(25)
		[Column,     Nullable] public string    Message     { get; set; } // text(255)
	}

	[Table("Order")]
	public partial class Order
	{
		[Column(),             PrimaryKey, Identity] public int       No         { get; set; } // Long
		[Column("uName"),      Nullable            ] public string    UName      { get; set; } // text(255)
		[Column("uPhone"),     Nullable            ] public string    UPhone     { get; set; } // text(255)
		[Column("uStartDate"), Nullable            ] public DateTime? UStartDate { get; set; } // DateTime
		[Column("uEndDate"),   Nullable            ] public DateTime? UEndDate   { get; set; } // DateTime
		[Column("uRoomType"),  Nullable            ] public string    URoomType  { get; set; } // text(255)
		[Column("isCheck"),                Identity] public bool      IsCheck    { get; set; } // Bit
		[Column("isEnble"),                Identity] public bool      IsEnble    { get; set; } // Bit
		[Column("uEmail"),     Nullable            ] public string    UEmail     { get; set; } // text(255)
		[Column("uNotes"),     Nullable            ] public string    UNotes     { get; set; } // text(255)
		[Column(),             Nullable            ] public string    Notes      { get; set; } // text(255)
	}

	public static partial class TableExtensions
	{
		public static About Find(this ITable<About> table, int No)
		{
			return table.FirstOrDefault(t =>
				t.No == No);
		}

		public static News Find(this ITable<News> table, int No)
		{
			return table.FirstOrDefault(t =>
				t.No == No);
		}

		public static Order Find(this ITable<Order> table, int No)
		{
			return table.FirstOrDefault(t =>
				t.No == No);
		}
	}
}
